person=input("Enter your name: ")
print("Hello",person)
password=input("Enter a Password: ")

x=input("Enter a number:")
y=input("Enter another number:")
a=(int(x)+int(y))
b=(int(x)/int(y))
c=(int(x)-int(y))
d=(int(x)*int(y))
print("Addition of Number= ",a)
print("Division of Number= ",b)
print("Subtraction of Number= ",c)
print("Multiplication of Number= ",d)